name: SonarQube Analysis

on:
  pull_request:
    branches:
      - qa

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
      - name: Build with Maven
        run: mvn clean install

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=<your_project_key> \
            -Dsonar.host.url=https://<your_sonarqube_server> \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
